### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by savin-alexey** [GreenMonkeyBoy/mean-angular2-authentication#2]
npm start ->>>>>
ERROR in /home/crisp/angular/greenm/node_modules/angular2-jwt/angular2-jwt.d.ts
(2,20): error TS2305: Module '"/home/crisp/angular/greenm/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'.
------------------------------------------------------------
 Error: The 2nd parameter to `mongoose.model()` should be a schema or a POJO
[1]     at Mongoose.model (/home/crisp/angular/greenm/node_modules/mongoose/lib/index.js:338:11)
[1]     at Object.<anonymous> (/home/crisp/angular/greenm/server.js:29:21)
[1]     at Module._compile (module.js:570:32)
[1]     at Object.Module._extensions..js (module.js:579:10)
[1]     at Module.load (module.js:487:32)
[1]     at tryModuleLoad (module.js:446:12)
[1]     at Function.Module._load (module.js:438:3)
[1]     at Module.runMain (module.js:604:10)
[1]     at run (bootstrap_node.js:394:7)
[1]     at startup (bootstrap_node.js:149:9)
[1]     at bootstrap_node.js:509:3
[1] [nodemon] app crashed - waiting for file changes before starting...

**Comment by rishabhrkaushik** [comment]
+1
Did you find the solution? @savin-alexey 
Please let me know.

**Comment by savin-alexey** [comment]
@rishabhrkaushik No ) 
ps. rm -rf/
